import type { Metadata } from 'next'
import { Comfortaa } from 'next/font/google'
import './globals.css'
import { Footer, SideNav, Providers, BottomNav } from './_global_components';

const poppins = Comfortaa({
  subsets: ['latin'],
  weight: [ '300', '400', '500', '600', '700', ]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{scrollBehavior:'smooth'}}>
      <body className={poppins.className}>
        <Providers>
          <div className="fixed hidden sm:block">
            <SideNav />
          </div>
          <div className="sm:ml-[91px] relative min-h-screen pb-[164px] sm:pb-[56px]">
            {children}
            <Footer />
          </div>
          <div className=" sm:hidden">
            <BottomNav />
          </div>
        </Providers>
      </body>
    </html>
  )
}
